# Generated by Django 5.0.2 on 2024-05-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Time',
        ),
    ]
