# Generated by Django 5.0.2 on 2024-05-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_appointment_date_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10000)),
                ('Email', models.CharField(max_length=10000)),
                ('Phone', models.CharField(max_length=10000)),
                ('Doctor', models.CharField(max_length=10000)),
                ('Date', models.CharField(max_length=10000)),
                ('Time', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
