# Generated by Django 5.0.2 on 2024-05-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_appointments_delete_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appoint',
        ),
    ]
